version: "3.9"
 
services:
  db:
    image: postgres
    container_name: bookcircle
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
 
volumes:
  pgdb: